CREATE TABLE cost (
     cost_id					INTEGER		NOT NULL , 
     cost_event_id				INTEGER     NOT NULL ,
     cost_domain_id				VARCHAR(20)	NOT NULL ,
     cost_type_concept_id		INTEGER		NOT NULL ,
     currency_concept_id		INTEGER		NULL ,
     total_charge				NUMERIC		NULL , 
     total_cost					NUMERIC		NULL , 
     total_paid					NUMERIC		NULL , 
     paid_by_payer				NUMERIC		NULL , 
     paid_by_patient			NUMERIC		NULL , 
     paid_patient_copay			NUMERIC		NULL , 
     paid_patient_coinsurance	NUMERIC		NULL , 
     paid_patient_deductible	NUMERIC		NULL , 
     paid_by_primary			NUMERIC		NULL , 
     paid_ingredient_cost		NUMERIC		NULL , 
     paid_dispensing_fee		NUMERIC		NULL , 
     payer_plan_period_id		INTEGER		NULL ,
     amount_allowed				NUMERIC		NULL , 
     revenue_code_concept_id	INTEGER		NULL , 
     revenue_code_source_value	VARCHAR(50)	NULL
);
